#!/bin/bash
##-------------------------------------------------------------------
## @copyright 2013 ShopEx Network Technology Co,.Ltd
## File : hello
## Author : filebat <markfilebat@126.com>
## Description :
## --
## Created : <`(format-time-string "%Y-%m-%d" (current-time))`>
## Updated: Time-stamp: <2013-01-28 15:55:44>
##-------------------------------------------------------------------

## File : hello ends
