#!/usr/bin/ruby
##-------------------------------------------------------------------
## @copyright 2016 DennyZhang.com
## Licensed under MIT 
##   https://raw.githubusercontent.com/DennyZhang/devops_public/master/LICENSE
##
## File : hello
## Author : Denny <denny@dennyzhang.com>
## Description :
## --
## Created : <`(format-time-string "%Y-%m-%d" (current-time))`>
## Updated: Time-stamp: <2016-04-20 12:04:34>
##-------------------------------------------------------------------
puts "hello, world"
## File : hello ends
