#!/usr/bin/ruby
##-------------------------------------------------------------------
## @copyright 2014 DennyZhang.com
## File : hello
## Author : Denny <denny.zhang001@gmail.com>
## Description :
## --
## Created : <`(format-time-string "%Y-%m-%d" (current-time))`>
## Updated: Time-stamp: <2014-06-15 18:40:38>
##-------------------------------------------------------------------
puts "hello, world"
## File : hello ends
